/*
{
   "id":"eb9b7414-a399-446b-9342-60675d069417",
   "kahoot":{
      "cover":"",
      "created":1606674003554,
      "description":"",
      "folderId":"",
      "introVideo":"",
      "language":"English",
      "metadata":{
         "moderation":{
            "flaggedTimestamp":0,
            "timestampResolution":0
         },
         "access":{
            "groupRead":[
               
            ],
            "folderGroupIds":[
            ]
         },
         "duplicationProtection":false,
         "lastEdit":{
            "editorUserId":"c41089ce-cdb0-41e6-b17c-32712bd80d5d",
            "editorUsername":"PrideofIndia",
            "editTimestamp":1606674098439
         }
      },
      "questions":[
         {
            "question":"Test Question Single Cjhopice",
            "type":"quiz",
            "layout":"CLASSIC",
            "choices":[
               {
                  "answer":"First",
                  "correct":false
               },
               {
                  "answer":"Secodn",
                  "correct":false
               },
               {
                  "answer":"Thirs",
                  "correct":false
               },
               {
                  "answer":"D",
                  "correct":false
               }
            ],
            "numberOfAnswers":4,
            "questionFormat":0,
            "resources":"",
            "time":20000,
            "video":{
               "fullUrl":"",
               "startTime":0,
               "endTime":0
            },
            "pointsMultiplier":1
         },
         {
            "question":"Second Querstions",
            "type":"quiz",
            "layout":"CLASSIC",
            "choices":[
               {
                  "answer":"Answyey q",
                  "correct":false
               },
               {
                  "answer":"BBBBB",
                  "correct":false
               },
               {
                  "answer":"CCC",
                  "correct":true
               },
               {
                  "answer":"DDDDD",
                  "correct":false
               }
            ],
            "numberOfAnswers":4,
            "questionFormat":0,
            "resources":"",
            "time":20000,
            "video":{
               "fullUrl":"",
               "startTime":0,
               "endTime":0
            },
            "pointsMultiplier":1
         },
         {
            "question":"Are you Inelligenct",
            "type":"quiz",
            "layout":"TRUE_FALSE",
            "choices":[
               {
                  "answer":"True",
                  "correct":true
               },
               {
                  "answer":"False",
                  "correct":false
               }
            ],
            "numberOfAnswers":2,
            "questionFormat":0,
            "resources":"",
            "time":20000,
            "video":{
               "fullUrl":"",
               "startTime":0,
               "endTime":0
            },
            "pointsMultiplier":1
         },
         {
            "question":"",
            "type":"multiple_select_quiz",
            "layout":"CLASSIC",
            "choices":[
               {
                  "answer":"AAAA",
                  "correct":true
               },
               {
                  "answer":"AVBBB",
                  "correct":false
               },
               {
                  "answer":"ASBCFDFGDG",
                  "correct":true
               },
               {
                  "answer":"Addfsdfsdf",
                  "correct":false
               }
            ],
            "numberOfAnswers":4,
            "questionFormat":0,
            "resources":"",
            "time":20000,
            "video":{
               "fullUrl":"",
               "startTime":0,
               "endTime":0
            },
            "pointsMultiplier":1
         }
      ],
      "quizType":"quiz",
      "resources":"",
      "title":"Enter kahoot title…",
      "type":"quiz",
      "visibility":0,
      "uuid":"eb9b7414-a399-446b-9342-60675d069417",
      "creator_username":"PrideofIndia",
      "creator":"c41089ce-cdb0-41e6-b17c-32712bd80d5d",
      "creator_primary_usage":"social",
      "lobby_video":{
         "youtube":{
            "id":"",
            "fullUrl":"",
            "startTime":0
         }
      },
      "themeId":null
   },
   "kahootExists":false
}



///


//"type":"multiple_select_quiz",
//  "layout":"CLASSIC",="TRUE_FALSE"
 "questions":[
         {
            "question":"Zaid Ahmad Khan",
            "type":"quiz",
            "layout":"CLASSIC",
            "choices":[
               {
                  "answer":"gfdgfdgf",
                  "correct":false
               },
               {
                  "answer":"dfgfdgfdg",
                  "correct":false
               },
               {
                  "answer":"sdfgfdg",
                  "correct":true
               },
               {
                  "answer":"dfgfdg",
                  "correct":false
               }
            ],
            "numberOfAnswers":4,
            "questionFormat":0,
            "resources":"",
            "time":20000,
            "video":{
               "fullUrl":"",
               "startTime":0,
               "endTime":0
            },
            "pointsMultiplier":1
         }
      ],
*/